export const ADD_THEME_VAR = 'ADD_THEME_VAR';
export const REMOVE_THEME_VAR = 'REMOVE_THEME_VAR';
export const UPDATE_THEME_VAR = 'UPDATE_THEME_VAR';
export const ADD_MAPPING = 'ADD_MAPPING';
export const REMOVE_MAPPING = 'REMOVE_MAPPING';
export const UPDATE_MAPPING = 'UPDATE_MAPPING';
export const ADD_THEME = 'ADD_THEME';
export const REMOVE_THEME = 'REMOVE_THEME';
export const SET_THEME_NAME = 'SET_THEME_NAME';
export const SET_THEME_VAL = 'SET_THEME_VAL';
export const RESET_STATE = 'RESET_STATE';

export default {
  ADD_THEME_VAR,
  REMOVE_THEME_VAR,
  UPDATE_THEME_VAR,
  ADD_MAPPING,
  REMOVE_MAPPING,
  UPDATE_MAPPING,
  ADD_THEME,
  REMOVE_THEME,
  SET_THEME_NAME,
  SET_THEME_VAL,
  RESET_STATE,
};
